### ISSUE TITLE
Cannot run docker commands inside slave

### ISSUE THREAD

**Issue by ryanwalls** [tehranian/dind-jenkins-slave#4]
I configure my build to have an "execute shell" step where I call `docker ps` to test it out.

Here's the console output:
```
Started by user ryanwalls
Building remotely on 2462e439f023@docker (docker-slave) in workspace /home/jenkins/workspace/login-app-build
Cloning the remote Git repository
Cloning repository <snip>
...

[login-app-build] $ /bin/sh -xe /tmp/hudson5600615388896400359.sh
+ docker ps
time="2015-04-01T19:23:45Z" level="fatal" msg="Get http:///var/run/docker.sock/v1.17/containers/json: dial unix /var/run/docker.sock: no such file or directory. Are you trying to connect to a TLS-enabled daemon without TLS?" 
Build step 'Execute shell' marked build as failure
Finished: FAILURE
```

Running the docker slave seems to work if I just use the Docker Plugin to build a dockerfile on the slave.  But I cannot execute docker commands directly.

**Comment by tehranian** [comment]
Can you confirm which user is succeeds as vs which user it fails as? 

Also, can you confirm ownership & mode of `/var/run/docker.sock`?

Thanks!
Dan

**Comment by t5unamie** [comment]
Hi There,

I get the same issue.

/var/run/docker.sock is owned by root.
Docker version outside of container - 1.5

The difference between me and the original poster is that I am trying to use Cloudbee's build & publishing to build the image on the slave and it;s failing with a similar error in the console.

I get the following error via running docker comands in the container.

ln: failed to create symbolic link '/sys/fs/cgroup/systemd/name=systemd': Operation not permitted
INFO[0000] +job serveapi(unix:///var/run/docker.sock)
INFO[0000] Listening for HTTP on unix (/var/run/docker.sock)
WARN[0000] WARNING: Udev sync is not supported. This will lead to unexpected behavior, data loss and errors
ERRO[0000] There are no more loopback devices available.
FATA[0000] loopback mounting failed
I get the following error via Jenkins console logs.

Started by user John P
Building remotely on cf9c2bec9bf8@Master node (jenkins-slaves) in workspace /home/jenkins/workspace/secret
Cloning the remote Git repository
Cloning repository secret
> git init secret # timeout=10
Fetching upstream changes from secret
> git --version # timeout=10
using GIT_SSH to set credentials secret
> git -c core.askpass=true fetch --tags --progress secret +refs/heads/*:refs/remotes/origin/*
> git config remote.origin.url secret # timeout=10
> git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10
> git config remote.origin.url secret # timeout=10
Fetching upstream changes from secret
using GIT_SSH to set credentials Innersource access
> git -c core.askpass=true fetch --tags --progress secret +refs/heads/*:refs/remotes/origin/*
> git rev-parse refs/remotes/origin/master^{commit} # timeout=10
> git rev-parse refs/remotes/origin/origin/master^{commit} # timeout=10
Checking out Revision secret (refs/remotes/origin/master)
> git config core.sparsecheckout # timeout=10
> git checkout -f secret
First time build. Skipping changelog.
[Build Devopstools] $ docker login -u secret -e secret -p ******** http://docker.secret.com/v1/
time="2015-04-14T11:38:33Z" level="fatal" msg="Post http:///var/run/docker.sock/v1.17/auth: dial unix /var/run/docker.sock: no such file or directory. Are you trying to connect to a TLS-enabled daemon without TLS?" 
[Build Devopstools] $ docker build -t secret:v12 .
Sending build context to Docker daemon 
time="2015-04-14T11:38:33Z" level="fatal" msg="Post http:///var/run/docker.sock/v1.17/build?dockerfile=Dockerfile&rm=1&t=secretv12: dial unix /var/run/docker.sock: no such file or directory" 
[Build Devopstools] $ docker push secret:v12
time="2015-04-14T11:38:34Z" level="fatal" msg="Post http:///var/run/docker.sock/v1.17/images/secret/push?tag=v12: dial unix /var/run/docker.sock: no such file or directory" 
Build step 'Docker Build and Publish' marked build as failure
Finished: FAILURE

Regards

John

**Comment by t5unamie** [comment]
Anyone know whats going on?

**Comment by wharfedale01** [comment]
I'm having the same problem, i use the mesos plugin. Any news?

**Comment by jmzuazo** [comment]
I have the same problem and the solution was to change docker.sock group to jenkins.

# chown root:jenkins /var/run/docker.sock

**Comment by morvans** [comment]
I can not run any "docker" command inside the running container. It seems that the Jenkins Docker Plugin override the default CMD to run only the SSH server.
A "ps" command executed as part of the job does not show any running docker daemon which seems to explain why docker commands won't work.
Setting the CMD from the Dockerfile in Jenkins Docker Plugin make Jenkins unable to start the conatainer up (seems stuck at startup, the container starts ok but the job doesn't start).

**Comment by yakhyadabo** [comment]
I have the same issue when trying to use jenkins slave with DinD pattern.
